# Start from a clean Linux base
FROM ubuntu:22.04

# Install dependencies
RUN apt update && apt install -y \
    build-essential \
    git \
    valgrind \
    libreadline-dev \
    libglfw3 \
    libglfw3-dev \
    cmake \
    nano \
    x11-xserver-utils \
    && rm -rf /var/lib/apt/lists/*

# Create folders
RUN mkdir -p /workspace/miniRT

# Set working directory to /workspace for interactive shells
WORKDIR /workspace

# Clone project inside /workspace/miniRT
RUN git clone https://github.com/RJW-db/MiniRT.git /workspace/miniRT
